name: 'google_ads_integration_tests'
version: '0.7.0'
profile: 'integration_tests'
config-version: 2

vars:
  google_ads__final_url_performance: "{{ ref('google_ads_final_url_performance_data') }}"
  google_ads__click_performance: "{{ ref('google_ads_click_performance_data') }}"
  google_ads__criteria_performance: "{{ ref('google_ads_criteria_performance_data') }}"
  google_ads__ad_stats: "{{ ref('google_ads_ad_stats_data') }}"
  google_ads__ad_history: "{{ ref('google_ads_ad_history_data') }}"
  google_ads__ad_group_history: "{{ ref('google_ads_ad_group_history_data') }}"
  google_ads__campaign_history: "{{ ref('google_ads_campaign_history_data') }}"
  google_ads__account_history: "{{ ref('google_ads_account_history_data') }}"

seeds:
  google_ads_integration_tests:
    google_ads_click_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        criteria_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_criteria_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_final_url_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_stats_data:
      +column_types:
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_campaign_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_group_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
